// このファイルは scripts/build-shelters.mjs が自動生成する（手で編集しないこと）。
// 兵庫県の市町村ごとに、国土地理院の公式CSVをビルド時に読み込めたかどうか。
// 解釈（available/unavailable/unknown）は lib/shelter/dataCompleteness.ts を参照。

import type { ShelterDatasetPresence } from "../dataCompleteness.ts";

export const HYOGO_SHELTER_DATASET_PRESENCE: Record<string, ShelterDatasetPresence> = {
  "28100": { emergencyEvacuationSites: true, designatedShelters: true },
  "28201": { emergencyEvacuationSites: true, designatedShelters: true },
  "28202": { emergencyEvacuationSites: true, designatedShelters: true },
  "28203": { emergencyEvacuationSites: true, designatedShelters: true },
  "28204": { emergencyEvacuationSites: true, designatedShelters: true },
  "28205": { emergencyEvacuationSites: true, designatedShelters: true },
  "28206": { emergencyEvacuationSites: true, designatedShelters: true },
  "28207": { emergencyEvacuationSites: true, designatedShelters: true },
  "28208": { emergencyEvacuationSites: true, designatedShelters: true },
  "28209": { emergencyEvacuationSites: true, designatedShelters: true },
  "28210": { emergencyEvacuationSites: true, designatedShelters: true },
  "28212": { emergencyEvacuationSites: true, designatedShelters: true },
  "28213": { emergencyEvacuationSites: true, designatedShelters: true },
  "28214": { emergencyEvacuationSites: true, designatedShelters: true },
  "28215": { emergencyEvacuationSites: true, designatedShelters: true },
  "28216": { emergencyEvacuationSites: true, designatedShelters: true },
  "28217": { emergencyEvacuationSites: true, designatedShelters: true },
  "28218": { emergencyEvacuationSites: true, designatedShelters: true },
  "28219": { emergencyEvacuationSites: true, designatedShelters: true },
  "28220": { emergencyEvacuationSites: true, designatedShelters: true },
  "28221": { emergencyEvacuationSites: true, designatedShelters: true },
  "28222": { emergencyEvacuationSites: true, designatedShelters: true },
  "28223": { emergencyEvacuationSites: true, designatedShelters: true },
  "28224": { emergencyEvacuationSites: true, designatedShelters: true },
  "28225": { emergencyEvacuationSites: true, designatedShelters: true },
  "28226": { emergencyEvacuationSites: true, designatedShelters: true },
  "28227": { emergencyEvacuationSites: true, designatedShelters: true },
  "28228": { emergencyEvacuationSites: true, designatedShelters: true },
  "28229": { emergencyEvacuationSites: true, designatedShelters: true },
  "28301": { emergencyEvacuationSites: true, designatedShelters: true },
  "28365": { emergencyEvacuationSites: true, designatedShelters: true },
  "28381": { emergencyEvacuationSites: true, designatedShelters: true },
  "28382": { emergencyEvacuationSites: true, designatedShelters: true },
  "28442": { emergencyEvacuationSites: true, designatedShelters: true },
  "28443": { emergencyEvacuationSites: true, designatedShelters: true },
  "28446": { emergencyEvacuationSites: true, designatedShelters: true },
  "28464": { emergencyEvacuationSites: true, designatedShelters: true },
  "28481": { emergencyEvacuationSites: true, designatedShelters: true },
  "28501": { emergencyEvacuationSites: true, designatedShelters: true },
  "28585": { emergencyEvacuationSites: true, designatedShelters: true },
  "28586": { emergencyEvacuationSites: true, designatedShelters: true },
};
