// このファイルは scripts/build-shelters.mjs が自動生成する（手で編集しないこと）。
// 大阪府の市町村ごとに、国土地理院の公式CSVをビルド時に読み込めたかどうか。
// 解釈（available/unavailable/unknown）は lib/shelter/dataCompleteness.ts を参照。

import type { ShelterDatasetPresence } from "../dataCompleteness.ts";

export const OSAKA_SHELTER_DATASET_PRESENCE: Record<string, ShelterDatasetPresence> = {
  "27100": { emergencyEvacuationSites: true, designatedShelters: true },
  "27140": { emergencyEvacuationSites: true, designatedShelters: true },
  "27202": { emergencyEvacuationSites: true, designatedShelters: true },
  "27203": { emergencyEvacuationSites: true, designatedShelters: true },
  "27204": { emergencyEvacuationSites: true, designatedShelters: true },
  "27205": { emergencyEvacuationSites: true, designatedShelters: true },
  "27206": { emergencyEvacuationSites: true, designatedShelters: true },
  "27207": { emergencyEvacuationSites: true, designatedShelters: true },
  "27208": { emergencyEvacuationSites: true, designatedShelters: true },
  "27209": { emergencyEvacuationSites: true, designatedShelters: true },
  "27210": { emergencyEvacuationSites: true, designatedShelters: true },
  "27211": { emergencyEvacuationSites: true, designatedShelters: true },
  "27212": { emergencyEvacuationSites: true, designatedShelters: true },
  "27213": { emergencyEvacuationSites: true, designatedShelters: true },
  "27214": { emergencyEvacuationSites: true, designatedShelters: true },
  "27215": { emergencyEvacuationSites: true, designatedShelters: true },
  "27216": { emergencyEvacuationSites: true, designatedShelters: true },
  "27217": { emergencyEvacuationSites: true, designatedShelters: true },
  "27218": { emergencyEvacuationSites: true, designatedShelters: true },
  "27219": { emergencyEvacuationSites: true, designatedShelters: true },
  "27220": { emergencyEvacuationSites: true, designatedShelters: true },
  "27221": { emergencyEvacuationSites: true, designatedShelters: true },
  "27222": { emergencyEvacuationSites: true, designatedShelters: true },
  "27223": { emergencyEvacuationSites: true, designatedShelters: true },
  "27224": { emergencyEvacuationSites: true, designatedShelters: true },
  "27225": { emergencyEvacuationSites: true, designatedShelters: true },
  "27226": { emergencyEvacuationSites: true, designatedShelters: true },
  "27227": { emergencyEvacuationSites: true, designatedShelters: true },
  "27228": { emergencyEvacuationSites: true, designatedShelters: true },
  "27229": { emergencyEvacuationSites: true, designatedShelters: true },
  "27230": { emergencyEvacuationSites: true, designatedShelters: true },
  "27231": { emergencyEvacuationSites: true, designatedShelters: true },
  "27232": { emergencyEvacuationSites: true, designatedShelters: true },
  "27301": { emergencyEvacuationSites: true, designatedShelters: true },
  "27321": { emergencyEvacuationSites: true, designatedShelters: true },
  "27322": { emergencyEvacuationSites: true, designatedShelters: true },
  "27341": { emergencyEvacuationSites: true, designatedShelters: true },
  "27361": { emergencyEvacuationSites: true, designatedShelters: true },
  "27362": { emergencyEvacuationSites: true, designatedShelters: true },
  "27366": { emergencyEvacuationSites: true, designatedShelters: true },
  "27381": { emergencyEvacuationSites: true, designatedShelters: true },
  "27382": { emergencyEvacuationSites: true, designatedShelters: true },
  "27383": { emergencyEvacuationSites: true, designatedShelters: true },
};
